CREATE TABLE `interests` (
  `intId` int(11) NOT NULL AUTO_INCREMENT,
  `fk_userId` varchar(20) DEFAULT NULL,
  `sports` tinyint(4) DEFAULT '0',
  `activity` tinyint(4) DEFAULT '0',
  `writing` tinyint(4) DEFAULT '0',
  `study` tinyint(4) DEFAULT '0',
  `exhibition` tinyint(4) DEFAULT '0',
  `music` tinyint(4) DEFAULT '0',
  `movie` tinyint(4) DEFAULT '0',
  `diy` tinyint(4) DEFAULT '0',
  `volunteer` tinyint(4) DEFAULT '0',
  `picture` tinyint(4) DEFAULT '0',
  `game` tinyint(4) DEFAULT '0',
  `cooking` tinyint(4) DEFAULT '0',
  `coffee` tinyint(4) DEFAULT '0',
  `nail` tinyint(4) DEFAULT '0',
  `car` tinyint(4) DEFAULT '0',
  `interior` tinyint(4) DEFAULT '0',
  `concert` tinyint(4) DEFAULT '0',
  `etc` tinyint(4) DEFAULT '0',
  `interestscol` varchar(45) DEFAULT '0',
  PRIMARY KEY (`intId`),
  KEY `fk_userId_idx` (`fk_userId`),
  CONSTRAINT `fk_userId2` FOREIGN KEY (`fk_userId`) REFERENCES `users` (`userId`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
