CREATE TABLE `test`.`interests` (
  `intId` INT NOT NULL AUTO_INCREMENT,
  `fk_userId` VARCHAR(20) NULL,
  `sports` TINYINT NOT NULL DEFAULT 0,
  `activity` TINYINT NOT NULL DEFAULT 0,
  `writing` TINYINT NOT NULL DEFAULT 0,
  `study` TINYINT NOT NULL DEFAULT 0,
  `exhibition` TINYINT NOT NULL DEFAULT 0,
  `music` TINYINT NOT NULL DEFAULT 0,
  `movie` TINYINT NOT NULL DEFAULT 0,
  `diy` TINYINT NOT NULL DEFAULT 0,
  `volunteer` TINYINT NOT NULL DEFAULT 0,
  `picture` TINYINT NOT NULL DEFAULT 0,
  `game` TINYINT NOT NULL DEFAULT 0,
  `cooking` TINYINT NOT NULL DEFAULT 0,
  `coffee` TINYINT NOT NULL DEFAULT 0,
  `nail` TINYINT NOT NULL DEFAULT 0,
  `car` TINYINT NOT NULL DEFAULT 0,
  `interior` TINYINT NOT NULL DEFAULT 0,
  `concert` TINYINT NOT NULL DEFAULT 0,
  `etc` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`intId`),
  INDEX `fk_userId_idx` (`fk_userId` ASC) VISIBLE,
  CONSTRAINT `fk_userId2`
    FOREIGN KEY (`fk_userId`)
    REFERENCES `test`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
